services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: commerce
      POSTGRES_USER: commerce
      POSTGRES_PASSWORD: commerce
    ports:
      - "5432:5432"
    volumes:
      - tmo-postgres-data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U commerce -d commerce"]
      interval: 5s
      timeout: 5s
      retries: 5

  identity:
    build:
      context: ../..
      dockerfile: services/identity/Dockerfile
    image: ${IMAGE_REPO:-tmo}/identity:${IMAGE_TAG:-dev}
    environment:
      IDENTITY_HTTP_ADDR: ":8081"
      IDENTITY_DB_DSN: "postgres://commerce:commerce@postgres:5432/identity?sslmode=disable"
      IDENTITY_LOG_LEVEL: "info"
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy

  commerce:
    build:
      context: ../..
      dockerfile: services/commerce/Dockerfile
    image: ${IMAGE_REPO:-tmo}/commerce:${IMAGE_TAG:-dev}
    environment:
      COMMERCE_HTTP_ADDR: ":8080"
      COMMERCE_DB_DSN: "postgres://commerce:commerce@postgres:5432/commerce?sslmode=disable"
      COMMERCE_LOG_LEVEL: "info"
    ports:
      - "8082:8080"
    depends_on:
      postgres:
        condition: service_healthy

  payment:
    build:
      context: ../..
      dockerfile: services/payment/Dockerfile
    image: ${IMAGE_REPO:-tmo}/payment:${IMAGE_TAG:-dev}
    environment:
      PAYMENT_HTTP_ADDR: ":8083"
      PAYMENT_LOG_LEVEL: "info"
      PAYMENT_IDENTITY_BASE_URL: "http://identity:8081"
      PAYMENT_AUTH_ENABLED: "false"
    ports:
      - "8083:8083"
    depends_on:
      identity:
        condition: service_started

  gateway-bff:
    build:
      context: ../..
      dockerfile: services/gateway-bff/Dockerfile
    image: ${IMAGE_REPO:-tmo}/gateway-bff:${IMAGE_TAG:-dev}
    environment:
      GATEWAY_HTTP_ADDR: ":8080"
      GATEWAY_IDENTITY_BASE_URL: "http://identity:8081"
      GATEWAY_COMMERCE_BASE_URL: "http://commerce:8080"
      GATEWAY_PAYMENT_BASE_URL: "http://payment:8083"
      GATEWAY_LOG_LEVEL: "info"
    ports:
      - "8080:8080"
    depends_on:
      identity:
        condition: service_started
      commerce:
        condition: service_started
      payment:
        condition: service_started

volumes:
  tmo-postgres-data:
